### ISSUE TITLE
(phi0474.phi006.perseus-lat/eng-1) EpiDoc and CTS conversions

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-latinLit#139]
using examples of phi0474.phi001/002/003

- [x] convert revision description to change log (follow format of when before who)

- [x] convert refsDecl 

- [x] make section default hierarchy

- [x] check paragraphs against source book to be sure of placement

- [x] general cleanup of formatting and tags

**Comment by lcerrato** [comment]
@zachhimes 

Please take a look at the files mentioned above as examples to follow for these file conversions.

I think it would be great if you could revisit the prose in this batch. 

If you want to preserve your first pass of work on these files, I would stash those files from pull request 100 aside.

Make a new branch for this work from the current master.

Do not worry about 1) changing the names of these files 2) any cts files.

Let's use this thread to review the work. If you commit to this branch as you go I can give directed feedback.

**Comment by zachhimes** [comment]
@lcerrato I've noticed for phi0474.phi006.perseus-eng1.xml, there are instances where the value for n in the section milestones are skipped (for instance, n=10 or 12). Should these gaps in the values for n be corrected (i.e. instead of going from n=9 to n=11 to n=13, should the correct sequence be n=9, n=10, n=11)? Also, I have noticed that there are gap tags in file (this is due to the gaps in the latin text). Do you know what the value for the reason attribute should be? I would assume that reason="lost" makes the most sense, but I'm not sure if this is the intended purpose of this value for reason.

**Comment by lcerrato** [comment]
@zachhimes (Sorry -- I thought I answered this last night.)

In looking at the Latin, there are sections missing, not misnumbered. I went through this quickly yesterday and can clarify this if it's not clear where the missing sections should go. The book does not contain sections: these have to be added based on the Latin.

Gaps should =lost in most cases, yes.

**Comment by lcerrato** [comment]
added to branch (phi0474.phi00X)

**Comment by lcerrato** [comment]
1. readded commented old refsDecl
2. missing sections were not added to English version.
3. reordered change log for reading ease
4. checked English paragraphs
