### ISSUE TITLE
Catullus (phi0472.phi001.perseus-lat2.xml) has wrong link to scan (ref target)

### ISSUE THREAD

**Issue by annettegessner** [PerseusDL/canonical-latinLit#154]
Just stumbled upon the link to the scan of Catullus being wrong. How come? Do we care?

https://github.com/PerseusDL/canonical-latinLit/blob/master/data/phi0472/phi001/phi0472.phi001.perseus-lat2.xml
has 
`<ref target="https://archive.org/details/orationesrecogno01ciceuoft">Internet Archive</ref>`
which is Cicero, not Catullus.

The link to the correct edition on HathiTrust (as in Perseus Catalog) would be: 
http://hdl.handle.net/2027/uc1.32106005763302

**Comment by AlisonBabeu** [comment]
Well I'm glad to know that it is correct in the catalog, I'm not quite sure how this might have happened, but I don't think its a big deal to change.

**Comment by lcerrato** [comment]
Looks like just a cut & paste error? 
We haven't typically added this to the file headers: I usually submit suggestions for new or modified links to the catalog data repo for this reason. 
I don't think we want to maintain links in the text files themselves. That seems to be a duplication of effort.

**Comment by AlisonBabeu** [comment]
It does seem to be a duplication of effort and I believe in general that
the file headers don't have links, but I could be wrong.

**Comment by PonteIneptique** [comment]
The file generally comes from me, sorry. This one might be my fault but I
can't trace this change. I usually put the Internet archive link when I
need to check the structure and do change accordingly.

**Comment by balmas** [comment]
@PonteIneptique, while we're on the topic of this text,  @helmadik was wondering why the meter divs were reverted back to milestones in this version.  Do you recall if this was intentional, maybe because of conflicts with the citation scheme? Or was it just a general application of the methodology which makes anything not part of the citation scheme into milestones?

**Comment by helmadik** [comment]
Let me add that there are some sgml characters replaced as well, but it
would be really nice to have this as @met in a div, since that will make
them searchable by meter, like at mqdq.it.

Helma Dik
Department of Classics
University of Chicago

**Comment by PonteIneptique** [comment]
As far as I see in the old repository, it was already milestone : https://github.com/PerseusDL/canonical/blob/master_backup/CTS_XML_TEI/perseus/latinLit/phi0472/phi001/phi0472.phi001.perseus-lat1.xml

**Comment by PonteIneptique** [comment]
As far as the scan goes, it seems to have been introduced by https://github.com/PerseusDL/canonical-latinLit/commit/d7e93d1c7272271309c6e590a8e5a35d52d36bd0 . I'll make a PR to revert this. Must be some kind of copy past issue

**Comment by balmas** [comment]
It was the initial conversion to TEI 5 that had the meter turned into divs I believe. It's quite possible those were somehow reverted back before you did your conversion. Not a big deal really -- I we need to decide at some point if we want to implement any standards for representation of meter in the TEI or if we want to follow the HMT approach of using analytical exemplars for that.

**Comment by helmadik** [comment]
Dear Bridget and other mavens, (is this @PonteIneptique
<https://github.com/PonteIneptique> how that works?)


May I ask some more questions about these various versions:
-Can you confirm that the lack of div1 vs div2 etc. in the new version, but
instead div type="texpart" subtype=".." is an EpiDoc change?

- Is the mention of multiple line ##s for repeated lines, such as o Hymen
Hymenaee an EpiDoc change? (n="328 334 338 343 348 353 357.. ")

- I've never understood org="uniform" and sample="complete" -- but they
will be gone from the EpiDoc version?

Other question: Is the text made available at Perseus tufts, always the
same as in the repository? Probably not? Is the ultimate presentation on
the page, say of line numbers every 5 lines, output of XSLT transforms?

No urgency, but..

Many thanks in advance!
Helma

Helma Dik
Department of Classics
University of Chicago

**Comment by PonteIneptique** [comment]
You can ping us using either @ponteineptique and @balmas which are our github username :)

- yes. div1 and div2 were moved to div only because of our "new" epidoc policy.
- Repeated lines are forbidden by CapiTainS guidelines (which is a layer over epidoc and which is our current target of conversion for all texts). It should not remain in a finale version.

**Comment by helmadik** [comment]
Thankyou @ponteineptique (nice to use this since I can't tell with 100%
certainty from your gmail name which is your first and which is your last
name :-)

Do you mean that in the final version the repeated line will only appear
once in full in the document, and rendering engines need to re-render it?

The beauty of TEI, as always, is that the search and retrieval software is
left holding the bag:-)

And I have learned something about CapiTainS..
So thanks again-
Helma


Helma Dik
Department of Classics
University of Chicago

**Comment by PonteIneptique** [comment]
(The name is Thibault Clérice ;) )
In the finale version, each line will have a unique number identifier, and any indication of repetition will be cut down, except if you have a proposal which allows use to keep unique identifier (with not space.)

Feel free to ask question anytime, I am one github mention away ;)

**Comment by lcerrato** [comment]
Hi Helma,

> Other question: Is the text made available at Perseus tufts, always the
> same as in the repository? Probably not? Is the ultimate presentation on
> the page, say of line numbers every 5 lines, output of XSLT transforms?

There is currently no relationship between what's on the site and what's in GitHub.
As far as line breaks when, the Perseus 4 (WWW) presentation of texts was mainly governed by the card breaks, which are being commented out of the EpiDoc versions.

--Lisa
