### ISSUE TITLE
(phi0448.phi001.perseus-lat2:2.6.3) coicerent missing markup 

### ISSUE THREAD

**Issue by gcelano** [PerseusDL/canonical-latinLit#317]
shouldn't the cruces in †coicerent† be rendered as some markup?

**Comment by lcerrato** [comment]
@gcelano 
I was not looking for these in early conversion passes as they aren't in all of our texts. I learned to look for them later on. Most of the Latin has issues like this.

In terms of the typos, this is an early OCR'd text and is very messy. It would be ideal to gather all of the errors into one issue in order to manage the corrections more efficiently. 

Feel free to do a PR for any corrections — we are happy to have them.
