### ISSUE TITLE
Typo in Latin text urn:cts:latinLit:phi0631.phi002.perseus-lat4:31

### ISSUE THREAD

**Issue by FergusJPWalsh** [PerseusDL/canonical-latinLit#435]
[phi0631.phi002.perseus-lat4.xml](https://github.com/PerseusDL/canonical-latinLit/tree/ae36df4/data/phi0631/phi002/phi0631.phi002.perseus-lat4.xml)

The text reads:

> Nihil vi, nihil **secession** opus est;

which is nonsense. I have checked a print edition and it should be **secessione**

**Comment by lcerrato** [comment]
@FergusJPWalsh 
Thank you.

Ideally, we need a source edition for the work. It's clear this is a typo or scanning artifact, but it would be ideal to have a scanned page to reference in cases where we have less obvious problems (such as variants).

We are trying to either replace unsourced texts or find the correct bibliographic information for the text in order to keep hosting it.

Unsourced works should not have been moved in the Scaife Viewer and we'll be revisiting this in the future.
